### PR TITLE
Fix python 3.12

### PR DESCRIPTION
**Pull request by meejah**
Basically just https://github.com/warner/python-spake2/pull/16 but with newest stuff, and another take on the CI.

### CODE REVIEW

**Comment by aquacash5** [comment]
It seems that the issue with `ConfigParser` is in `versioneer`. Could we update to the latest version of `versioneer`, instead of patching the old version?

I'm not familiar with `versioneer` and when I tried updating it, I couldn't get the package to work.

**Comment by meejah** [comment]
Yeah, that likely makes more sense .. was just trying to get CI to run on the "existing" PR.

**Comment by meejah** [comment]
(Although I probably have to switch to a branch-in-warner/python-spake2 to get the GHA things to run I think?)

**Comment by meejah** [comment]
Replaced by #18

**Pull request closed without merging**
